version: "3"

services:
  api:
    container_name: coursesApi
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/api/src
    expose:
      - ${PORT}
    ports:
      - 3000:3000
    depends_on:
      - pg
    command: bash -c 'yarn migration:run && yarn dev'
  pg:
    container_name: coursesDb
    image: postgres
    env_file:
      - .env
    expose:
      - ${PGPORT}
    ports:
      - 5433:5433
